# Expects {sm}.fa
input_dir_asm: "test/inputs/asm"
# Expects {sm}.bam
input_dir_bam: "test/inputs/bam"

output_dir: "results"

samples:
  - "HG00171"

calculate_cov:
  threads: 8
  mem: 4
  biased_regions: {}

flagger:
  threads: 16
  mem: 4
