# Expects {sm}.fa
input_dir_asm: "test/asm"
# Expects {sm}.bam
input_dir_bam: "test/bam"

output_dir: "results"

samples:
  - "HG002v1.1"

calculate_cov:
  threads: 8
  mem: 4GB
  biased_regions: {}

flagger:
  threads: 8
  mem: 120GB
  alpha: "config/alpha_optimum_trunc_exp_gaussian_w_4000_n_50.tsv"
